[package]
name = "MofuBridge"
version = "1.0.0"
authors = []

[addresses]
bridge = "_"
# admin_addr = "_"

[dev-addresses]
bridge = "0x1234"
# admin_addr = "0x731e36c20fa090d98c5826cb0a99684158dd3c80b02aa8b60bd18e9cbb6e92d0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }
# AptosToken = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-token", rev = "mainnet" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-token-objects", rev = "mainnet" }

[dev-dependencies]